version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASS:-example}"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_ROOT_USER:-root}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_ROOT_PASS:-example}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_ROOT_USER:-root}:${MONGO_ROOT_PASS:-example}@mongo:27017/"
