webserverPort: 8080
debug: true
logLevel: info
jaegerURL: "http://localhost:14268/api/traces"
database:
  port: 27017
  host: localhost
  user: root
  password: example
  name: "aur_package_builder_api"
docker:
  auth: true
  username: <registry-username>
  password: <registry-password>
  registryUrl: <registry-url>